name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: yarn install

    # - name: Lint
    #   run: yarn lint

    - name: Test
      run: echo $EVENT
      env:
        EVENT: ${{ github.event.pull_request }}

    # Runs a set of commands using the runners shell
    # - name: Run tests
    #   run: yarn test
