name: CI

on: [push, pull_request]

jobs:
  build:
    outputs:
      lint_results: ${{ steps.lint.outputs.results }}

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Lint
      id: lint
      run: yarn --silent lint 

    # Runs a set of commands using the runners shell
    - name: Test
      run: yarn --silent test
  lint_results:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.lint_results }}

