name: CI

on: [push, pull_request]

jobs:
  build:
    outputs:
      lint_results: ${{ steps.lint.outputs.results }}

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Lint
      id: lint
      run: |
        yarn lint | tee lint_results
        echo "::set-output name=results::$(cat lint_results)"

    - name: Test
      run: echo $EVENT
      env:
        COMMENTS_URL: ${{ github.event.pull_request.comments_url }}

    # Runs a set of commands using the runners shell
    - name: Run tests
      run: yarn test
  lint_results:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: eco ${{ needs.build.outputs.lint_results }}

